import { PrismaClient, Prisma } from "@/generated/prisma";

const prisma = new PrismaClient();

const newsData: Prisma.NewsSummaryCreateInput[] = [
  {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
    {
    userId: "user Id",
    headline: "Headline Placeholder",
    aiRepsonse: "Response By AI",
    provider: "finnhub",
    category: "Category",
    language: "English",
    url: null,
    isByCategory: true,
  },
  
];

export async function main() {
  for (const news of newsData) {
    await prisma.newsSummary.create({ data: news });
  }
}

main();
